# $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Pro WFM Reporting Documentation
site_url: https://example.com
repo_name: nconklindev/birt-docs-mkdocs
repo_url: https://github.com/nconklindev/birt-docs-mkdocs
plugins:
  - search
markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - "BIRT Studio":
    - birt-studio/index.md

    - Introduction:
      - birt-studio/introduction/index.md
      - Getting Started: birt-studio/introduction/getting-started.md
      - Terminology: birt-studio/introduction/terminology.md
      - User Interface: birt-studio/introduction/user-interface.md
    - Customizing Reports:
      - birt-studio/customizing-reports/index.md
      - Editing and Formatting: birt-studio/customizing-reports/editing-and-formatting.md
      - Sorting: birt-studio/customizing-reports/sorting.md
      - Grouping: birt-studio/customizing-reports/grouping.md
      - Filtering: birt-studio/customizing-reports/filtering.md
      - Aggregating: birt-studio/customizing-reports/aggregating.md
    - Advanced:
      - birt-studio/advanced/index.md
      - Computed Columns: birt-studio/advanced/computed-columns.md
      - Adding CSV Format: birt-studio/advanced/csv-reports.md
      - Summary Tables: birt-studio/advanced/summary-tables.md
      - Custom Report Parameters: birt-studio/advanced/custom-report-parameters.md
      - Crosstab Reports: birt-studio/advanced/crosstab-reports.md
      - Time Series Reports: birt-studio/advanced/time-series-reports.md
      - Relative Time Period Reports: birt-studio/advanced/relative-time-period-reports.md
      - HCA Reports: birt-studio/advanced/hca-reports.md
    - Troubleshooting:
      - birt-studio/troubleshooting/index.md
      - Using Splash: birt-studio/troubleshooting/using-splash.md
      - Report Failures and Performance: birt-studio/troubleshooting/report-failures-and-performance.md
      - CSV Format: birt-studio/troubleshooting/csv-format.md
    - Best Practices: birt-studio/best-practices.md
    - "Known Issues": "birt-studio/known-issues.md"
    - FAQ: birt-studio/faq.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    # Toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: gold
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.prune
    - search.suggest
    - search.highlight
    - toc.follow
    - toc-integrate
  font:
    text: Inter
    code: JetBrains Mono
